services:
  postgres:
    image: postgres:14-alpine
    container_name: graphql-demo-postgres # This is used as the hostname for other containers
    volumes:
      - ~/.graphql-demo-docker-conf/postgresql:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
